const advisoryCommitteeMembers = [
  {
    name: "Prof. R. K. Buyya",
    place: "Melbourne University, Australia",
    imgSrc: "Prof. R. K. Buyya.jpg",
  },
  {
    name: "Prof. Manoj Misra",
    place: "IIT Roorkee",
    imgSrc: "Prof. Manoj Misra.jpg",
  },
  {
    name: "Prof. G. R. Sinha",
    place: "IISC Bangalore",
    imgSrc: "Prof. G. R. Sinha.jpg",
  },
  {
    name: "Prof. Rajeev Srivastava",
    place: "IIT BHU",
    imgSrc: "Prof. Rajeev Srivastava.jpg",
  },
  {
    name: "Prof. P. K. Mishra",
    place: "IIT BHU",
    imgSrc: "Prof. P. K. Mishra.jpg",
  },
  {
    name: "Prof. Shekhar Verma",
    place: "IIIT Prayagraj",
    imgSrc: "Prof. Shekhar Verma.jpg",
  },
  {
    name: "Prof. S. K. Singh",
    place: "IIT BHU",
    imgSrc: "Prof S K Singh.jpg",
  },
  {
    name: "Prof. R. S. Yadav",
    place: "NIT Prayagraj",
    imgSrc: "Prof R S Yadav.jpg",
  },
  {
    name: "Prof. S. K. Singh",
    place: "IIIT Prayagraj",
    imgSrc: "Prof S K Singh2.jpg",
  },
  {
    name: "Prof. Nanhay Singh",
    place: "NSUT New Delhi",
    imgSrc: "Prof. Nanhay Singh.jpg",
  },
  {
    name: "Prof. Vivek Sahai",
    place: "University of Lucknow",
    imgSrc: "Prof Vivek Sahai.jpg",
  },
  {
    name: "Prof. S. Singh",
    place: "PEC, Chandigarh",
    imgSrc: "Prof S. Singh.jpg",
  },
  {
    name: "Prof. Shiv Datt Kumar",
    place: "MNNIT Prayagraj",
    imgSrc: "Prof. Shiv Datt Kumar.jpg",
  },
  {
    name: "Prof. K. V. Arya",
    place: "IIIT Gwalior",
    imgSrc: "Prof. K. V. Arya.jpg",
  },
];

const technicalMembers = [
  { name: "Dr. Anurag Singh", place: "NIT Delhi" },
  { name: "Prof. Nanhay Singh", place: "NSUT New Delhi" },
  { name: "Dr. Gaurav Barnwal", place: "BHU Varanasi" },
  { name: "Dr. N. P. Singh", place: "NIT Jalandhar" },
  { name: "Prof. Divakar Yadav", place: "IGNOU New Delhi" },
  { name: "Dr. Sanjoy Das", place: "IGNTU MP" },
  { name: "Prof. Om Prakash", place: "IIT Patna" },
  { name: "Prof. R. S. Rao", place: "NSUT Delhi" },
  { name: "Dr. Karan Singh", place: "JNU New Delhi" },
  { name: "Dr. Anuj Kumar", place: "MNNIT Prayagraj" },
  { name: "Dr. Vaibhav Prakash", place: "MNNIT Prayagraj" },
  { name: "Dr. Ashish Shrivastava", place: "GLA Mathura" },
  { name: "Dr. Ashutosh Bhatt", place: "Uttarakhand Open University" },
  { name: "Dr. Awadhesh Kumar", place: "KNIT Sultanpur" },
  { name: "Dr. Updendra Kumar", place: "IET Lucknow" },
  { name: "Dr. Shashank Gupta", place: "BIET Jhansi" },
  { name: "Dr. Rajendra Kumar", place: "JMI New Delhi" },
  { name: "Dr. Ravi Sharma", place: "Galgotias University, Gr. Noida" },
  { name: "Dr. Anil Kr. Bisth", place: "MJP Rohelkhand University" },
  { name: "Dr. Vinay Gupta", place: "Guru Teg Bahadur University" },
  { name: "Dr. Imran Khan", place: "HBTI Kanpur" },
  { name: "Dr. Saurabh Rana", place: "Bennett University, Gr. Noida" },
  { name: "Dr. Hari Prabhat Gupta", place: "IIT BHU" },
  { name: "Dr. Pawan Chaurasiya", place: "BBAU Lucknow" },
  { name: "Dr. Saurabh Singh", place: "BHU Varanasi" },
  { name: "Dr. Mukesh Awasthi", place: "BBAU Lucknow" },
  { name: "Dr. Dharmendra Mishra", place: "MANIT Bhopal" },
  { name: "Dr. A. K. Verma", place: "IIT Patna" },
  { name: "Dr. Rakesh Chandra Joshi", place: "Amity University, Noida" },
  { name: "Dr. Chintan Mandal", place: "Jadavpur University" },
];

const publicityMembers = [
  { name: "Prof. S. P. Singh", post: "Convener" },
  { name: "Dr. Abhijeet Mishra", post: "Member" },
  { name: "Mrs. Hemlata", post: "Member" },
  { name: "Mr. K. K. Gautam", post: "Member" },
  { name: "Ms. Alka Maurya", post: "Member" },
  { name: "Ms. Nida Shakeel", post: "Member" },
  { name: "Mr. Saurabh Mishra", post: "Member" },
  { name: "Mr. Shivendra Kumar", post: "Member" },
  { name: "Mr. Dharmendra", post: "Member" },
  { name: "Ms. Sweetie Gupta", post: "Member" },
];

const organizingMembers = [
  { name: "Prof. Shiva Prakash", position: "Chairman" },
  { name: "Prof. S. P. Singh", position: "Co-Chairman" },
  { name: "Prof. U. C. Jaiswal", position: "Member" },
  { name: "Prof. D.S. Singh", position: "Member" },
  { name: "Dr. Jay Prakash", position: "Member" },
  { name: "Dr. R. K. Dwivedi", position: "Member" },
  { name: "Mr. Manish Kr. Gupta", position: "Member" },
  { name: "Ms. Kumud Patel", position: "Member" },
  { name: "Prof. V. K. Mishra", position: "Member" },
  { name: "Dr. A. K. Barnwal", position: "Member" },
  { name: "Dr. Harish Chandra", position: "Member" },
  { name: "Mr. Vijay Kumar Tiwari", position: "Member" },
  { name: "Ms. Preeti Singh", position: "Member" },
  { name: "Ms. Pranjal Maurya", position: "Member" },
  { name: "Ms. Prachi Verma", position: "Member" },
];

const hospitalityMembers = [
  { name: "Dr. D. S. Singh", role: "Convener" },
  { name: "Dr. Jay Prakash", role: "Member" },
  { name: "Mr. Vijay Kumar Tiwari", role: "Member" },
  { name: "Ms. Prachi Verma", role: "Member" },
  { name: "Ms. Preeti Singh", role: "Member" },
  { name: "Ms. Pranjal Maurya", role: "Member" },
  { name: "Mr. Sanjeev Kumar Singh", role: "Member" },
  { name: "Ms. Ritu Singh", role: "Member" },
  { name: "Ms. Neelam Chauhan", role: "Member" },
  { name: "Ms. Anju Verma", role: "Member" },
  { name: "Mr. Durgesh Kr. Yadav", role: "Member" },
  { name: "Mr. Sumit Kumar", role: "Member" },
  { name: "Ms. Niharika Singh", role: "Member" },
  { name: "Ms. Akansha Singh", role: "Member" },
  { name: "Ms. Lacchita Soni", role: "Member" },
  { name: "Mr. Shivendra Kumar", role: "Member" },
  { name: "Mr. Saurabh Mishra", role: "Member" },
  { name: "Ms. Sweetie Gupta", role: "Member" },
];

const transportMembers = [
  { name: "Dr. Rajan Mishra", role: "Convener" },
  { name: "Mr. Vijay Kumar Tiwari", role: "Member" },
  { name: "Ms. Prachi Verma", role: "Member" },
  { name: "Ms. Ritu Singh", role: "Member" },
  { name: "Mr. Anand Kumar", role: "Member" },
  { name: "Mr. Dharmesh Sonkar", role: "Member" },
  { name: "Ms. Rajni Kumari", role: "Member" },
  { name: "Ms. Diksha Upadhyay", role: "Member" },
  { name: "Mr. Shivendra Kumar", role: "Member" },
  { name: "Mr. Saurabh Mishra", role: "Member" },
];

const innovationMembers = [
  { name: "Prof. U. C. Jaiswal", role: "Chairman" },
  { name: "Ms. Preeti Singh", role: "Member" },
  { name: "Ms. Pranjal Maurya", role: "Member" },
  { name: "Mr. K. M. Pathak", role: "Member" },
  { name: "Mr. K. K. Gautam", role: "Member" },
  { name: "Ms. Nida Shakeel", role: "Member" },
  { name: "Ms. Alka Maurya", role: "Member" },
  { name: "Mr. Saurabh Mishra", role: "Member" },
  { name: "Mr. Dharmendra", role: "Member" },
];
